els-ASAP auto commit file/tag opencryptoki-3.6.2-1.el7.src.rpm

diff --git a/src/testcases/ock_tests.sh.in b/src/testcases/ock_tests.sh.in
--- a/src/testcases/ock_tests.sh.in
+++ b/src/testcases/ock_tests.sh.in
@@ -1,11 +1,21 @@
 #!/bin/bash
 #
-# COPYRIGHT (c) International Business Machines Corp. 2008-2017
 #
-# This program is provided under the terms of the Common Public License,
-# version 1.0 (CPL-1.0). Any use, reproduction or distribution for this software
-# constitutes recipient's acceptance of CPL-1.0 terms which can be found
-# in the file LICENSE file or at https://opensource.org/licenses/cpl1.0.php
+#   Copyright (C) International Business Machines  Corp., 2008
+#
+#   This program is free software;  you can redistribute it and/or modify
+#   it under the terms of the GNU General Public License as published by
+#   the Free Software Foundation; either version 2 of the License, or
+#   (at your option) any later version.
+#
+#   This program is distributed in the hope that it will be useful,
+#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
+#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
+#   the GNU General Public License for more details.
+#
+#   You should have received a copy of the GNU General Public License
+#   along with this program;  if not, write to the Free Software
+#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 #
 #
 # NAME
@@ -31,7 +41,7 @@ LOGGING=0
 TESTDIR=`dirname $0`
 LOGFILE="$TESTDIR/ock-tests.log"
 ERR_SUMMARY="$TESTDIR/ock-tests.err"
-PKCONF="@sysconfdir@/opencryptoki/opencryptoki.conf"
+PKCONF="@localstatedir@/lib/opencryptoki/pk_config_data"
 PKCSCONFBIN="@sbindir@/pkcsconf"
 TESTCONF="$TESTDIR/ock-tests.config"
 TOKTYPE=""
@@ -48,23 +58,17 @@ NONEED_TOKEN_INIT=0
 # login/login MUST come last if it appears in this list
 #
 OCK_TESTS="crypto/*tests"
-OCK_TEST=""
 OCK_BENCHS="pkcs11/*bench"
 
 usage()
 {
-    echo -e " usage: ./ock_tests.sh [-s <slot>] [-f <testfile>]" \
-            "[-l <logfile>] [-n] [-h]"
-    echo -e "     -l <logfile>   redirect output to logfile" \
-            "(default is command line)"
-    echo -e "     -h             display this help"
-    echo -e "     -q             run quietly - display only total number" \
-            "of tests passed/failed"
-    echo -e "     -s <slot>      slot against which the testcases will run" \
-            "(omit it to test all available tokens)"
-    echo -e "     -f <testfile>  path to test that will be run"
-    echo -e "     -n             don't stop in case one of the testcases fail"
-    echo -e "     -b             also run benchmarks or performance tests"
+    echo -e "   usage: ./ock_tests.sh [-s <slot>] [-l <logfile>] [-n] [-h]"
+    echo -e "       -l          logfile to redirect output to (default is command line)"
+    echo -e "       -h          display this help"
+    echo -e "       -q          run quietly - display only total number of tests passed/failed"
+    echo -e "       -s <slot>   slot against which the testcases will run"
+    echo -e "       -n          don't stop in case one of the testcases fail"
+    echo -e "       -b          also run benchmarks or performance tests"
     exit -1
 }
 
@@ -115,7 +119,7 @@ init_slot()
                 return 1
             fi
             ;;
-        CCA | EP11 | ICA | Software)
+        CCA | ICA | Software)
             echo "Initializing $TOKTYPE using init_token.sh"
             if ! $TESTDIR/init_token.sh $1; then
                 echo "Error initializing $TOKTYPE token"
@@ -159,13 +163,9 @@ check_slot()
             echo "Software Token type detected"
             TOKTYPE="Software"
             ;;
-        *EP11*)
-            echo "EP11 Token type detected"
-            TOKTYPE="EP11"
-            ;;
         *)
             echo "Error: unsupported or undetermined token type"
-            echo "       wrong Slot $1?"
+            echo "       wrong Slot?"
             return 1
         esac
 
@@ -204,19 +204,16 @@ check_env()
         exit 1
     fi
 
-    # if user is not root
-    if [ $EUID -ne 0 ]; then
-        ## Check if the pkcs11 group 'exists'
-        P11GROUP=`getent group pkcs11 | cut -d ":" -f 3`
-        if [ -z $P11GROUP ]; then
-            echo "FATAL: Can't find pkcs11 group"
-            exit 1
-        fi
-        ## Check if we're part of it
-        if ! id -G | grep $P11GROUP; then
-            echo "FATAL: Must be part of the pkcs11 group"
-            exit 1
-        fi
+    ## Check if the pkcs11 group 'exists'
+    P11GROUP=`getent group pkcs11 | cut -d ":" -f 3`
+    if [ -z $P11GROUP ]; then
+        echo "FATAL: Can't find pkcs11 group"
+        exit 1
+    fi
+    ## Check if we're part of it
+    if ! id -G | grep $P11GROUP; then
+        echo "FATAL: Must be part of the pkcs11 group"
+        exit 1
     fi
 
     ## Make sure we have the slot daemon running
@@ -239,13 +236,10 @@ check_env()
 ###
 run_tests()
 {
-    if [ -n "$OCK_TEST" ]; then
-        OCK_TESTS="$OCK_TEST"
-    fi
     echo "***** Will run the following tests for slot $1: $(ls -U $OCK_TESTS)"
-    for j in $( ls -U $OCK_TESTS ); do
-        echo "** Now executing '$j'"
-        $j -slot $1 $NO_STOP 2>&1
+    for i in $( ls -U $OCK_TESTS ); do
+        echo "** Now executing '$i'"
+        $i -slot $1 $NO_STOP 2>&1
         RES=$?
 		if [ $RES -ne 0 ]; then
 			echo "ERROR: Testcase $i failed to execute."
@@ -267,44 +261,31 @@ run_benchs()
         $i -slot $1 $NO_STOP 2>&1
     done
 }
-
-
 main_script()
 {
-    LOGFILE=0
-
     # check generic stuff first
     check_env
 
     # where to run
     if [ -z $SLOT ]; then
-        NUMSLOT=$(grep '^slot' $PKCONF | wc -l)
+        NUMSLOT=`wc -l $PKCONF | cut -d " " -f 1`
         for ((i=0; i<$NUMSLOT; i++)); do
             SLOT="$SLOT $i"
-            LOGFILE=1
         done
     fi
 
-    for i in $SLOT; do (
+    for i in $SLOT; do
         echo "********** Testing Slot $i **********"
         check_slot $i || { echo "SKIPPING slot $i"; continue; }
         if [ $NONEED_TOKEN_INIT -eq 0 ]; then
             init_slot $i || { echo "SKIPPING slot $i"; continue; }
         fi
-        if [ "$LOGFILE" = "1" ]; then
-            echo "test output for slot $i stored in log-slot_$i.txt"
-            run_tests $i > "log-slot_$i.txt" 2>&1
-        else
-            run_tests $i
-        fi
+        run_tests $i
         [ -n "$BENCHMARK" ] && run_benchs $i
-        echo "********** Finished Testing Slot $i **********"
-        ) &
     done
-    wait
 }
 
-while getopts s:f:l:hc:n arg; do
+while getopts s:l:hc:n arg; do
     case $arg in
         h)
             usage
@@ -325,9 +306,6 @@ while getopts s:f:l:hc:n arg; do
             ;;
         s)
             SLOT="$OPTARG"
-            ;;
-        f)
-            OCK_TEST="$OPTARG"
             ;;
         b)
             BENCHMARK="yes"
